=== AngelShade/aion-server/game-server/data/static_data/decomposable_items/decomposable_items.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation="../items/item_templates.xsd" />
	<xs:element name="decomposable_items">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="decomposable" type="DecomposableItem" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="DecomposableItem">
		<xs:sequence>
			<xs:element name="set" type="DecomposableSet" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="item_id" type="itemId" use="required" />
		<xs:attribute name="selectable" type="xs:boolean" default="false" />
		<xs:attribute name="only_one" type="xs:boolean" default="false" />
		<xs:attribute name="override" type="xs:boolean" default="false" />
	</xs:complexType>
	<xs:complexType name="DecomposableSet">
		<xs:choice maxOccurs="unbounded">
			<xs:element name="item" type="DecomposedItem" />
			<xs:element name="bundle" type="DecomposedBundle" />
		</xs:choice>
		<xs:attribute name="chance" type="xs:float" default="100" />
		<xs:attribute name="min_level" type="xs:int" default="1" />
		<xs:attribute name="max_level" type="xs:int" default="80" />
		<xs:attribute name="race" type="Race" default="PC_ALL" />
		<xs:attribute name="player_classes" type="ListPlayerClass" />
	</xs:complexType>
	<xs:complexType name="DecomposedItem">
		<xs:attribute name="id" type="itemId" use="required" />
		<xs:attribute name="count" type="xs:int" default="1" />
		<xs:attribute name="max_count" type="xs:int" default="0" />
		<xs:attribute name="chance" type="xs:float" default="100" />
	</xs:complexType>
	<xs:complexType name="DecomposedBundle">
		<xs:sequence>
			<xs:element name="item" type="BundledItem" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="chance" type="xs:float" default="100" />
	</xs:complexType>
	<xs:complexType name="BundledItem">
		<xs:attribute name="id" type="itemId" use="required" />
		<xs:attribute name="count" type="xs:int" default="1" />
		<xs:attribute name="max_count" type="xs:int" default="0" />
	</xs:complexType>
	<xs:simpleType name="ListPlayerClass">
		<xs:list itemType="playerClass" />
	</xs:simpleType>
</xs:schema>

=== AngelShade/aion-server/target-deploy/game-server/data/static_data/decomposable_items/local_decomposable_items.xml
<?xml version="1.0" encoding="UTF-8"?>
<decomposable_items xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="decomposable_items.xsd">
	<!-- Local gameplay/restored-box overrides; provenance differs from the imported retail tables. -->
	<decomposable item_id="188052083" override="true">
		<set>
			<bundle>
				<item id="164000073" count="20" />
				<item id="164000076" count="20" />
				<item id="164000079" count="20" />
				<item id="162000023" count="10" />
				<item id="169000010" count="5000" />
				<item id="162000107" count="5" />
			</bundle>
		</set>
	</decomposable>
	<decomposable item_id="188052086" override="true">
		<set>
			<bundle chance="20">
				<item id="182400001" count="1000000" max_count="3000000" />
				<item id="188052083" />
			</bundle>
			<item id="162000107" count="10" max_count="25" chance="20" />
			<item id="188052213" chance="15" />
			<item id="188052088" chance="15" />
			<item id="188052077" chance="15" />
			<item id="162000023" count="10" max_count="30" chance="15" />
		</set>
	</decomposable>
	<decomposable item_id="188052088" override="true">
		<set>
			<bundle>
				<item id="162000080" count="15" />
				<item id="162000050" count="15" />
				<item id="162000023" count="15" />
			</bundle>
		</set>
	</decomposable>
	<decomposable item_id="188052187" override="true">
		<set>
			<item id="167000578" chance="3.7" />
			<item id="167000579" chance="3.7" />
			<item id="167000584" chance="3.5" />
			<item id="167000587" chance="3.5" />
			<item id="167000588" chance="3.5" />
			<item id="167000589" chance="3.5" />
			<item id="167000596" chance="3.5" />
			<item id="167000597" chance="3.5" />
			<item id="167000603" chance="3.5" />
			<item id="167000605" chance="3.5" />
			<item id="167000606" chance="3.5" />
			<item id="167000607" chance="3.5" />
			<item id="167000614" chance="2.8" />
			<item id="167000615" chance="2.8" />
			<item id="167000616" chance="2.8" />
			<item id="167000619" chance="2.8" />
			<item id="167000620" chance="2.8" />
			<item id="167000621" chance="2.8" />
			<item id="167000628" chance="2.8" />
			<item id="167000629" chance="2.8" />
			<item id="167000635" chance="2.8" />
			<item id="167000637" chance="2.8" />
			<item id="167000638" chance="2.8" />
			<item id="167000639" chance="2.8" />
			<item id="167000646" chance="2" />
			<item id="167000647" chance="2" />
			<item id="167000652" chance="2" />
			<item id="167000655" chance="2" />
			<item id="167000656" chance="2" />
			<item id="167000657" chance="2" />
			<item id="167000664" chance="2" />
			<item id="167000665" chance="2" />
			<item id="167000671" chance="2" />
			<item id="167000673" chance="2" />
			<item id="167000674" chance="2" />
			<item id="167000675" chance="2" />
		</set>
	</decomposable>
	<decomposable item_id="188052213" override="true">
		<set>
			<bundle>
				<item id="186000253" count="5" />
				<item id="162000107" count="5" />
				<item id="164000073" count="10" />
				<item id="164000076" count="10" />
				<item id="164000079" count="10" />
				<item id="162000080" count="10" />
			</bundle>
		</set>
	</decomposable>
	<decomposable item_id="188052361" override="true">
		<set>
			<bundle>
				<item id="186000253" count="5" />
				<item id="162000107" count="5" />
				<item id="164000073" count="10" />
				<item id="164000076" count="10" />
				<item id="164000079" count="10" />
				<item id="162000080" count="10" />
			</bundle>
		</set>
	</decomposable>
	<decomposable item_id="188052555" override="true">
		<set>
			<item id="167000682" chance="0.79" />
			<item id="167000683" chance="6.54" />
			<item id="167000684" chance="0.79" />
			<item id="167000685" chance="0.79" />
			<item id="167000686" chance="6.55" />
			<item id="167000687" chance="0.79" />
			<item id="167000688" chance="6.54" />
			<item id="167000689" chance="6.54" />
			<item id="167000690" chance="0.39" />
			<item id="167000691" chance="0.79" />
			<item id="167000692" chance="0.79" />
			<item id="167000693" chance="0.79" />
			<item id="167000694" chance="0.79" />
			<item id="167000695" chance="0.79" />
			<item id="167000696" chance="0.79" />
			<item id="167000697" chance="0.79" />
			<item id="167000698" chance="6.54" />
			<item id="167000699" chance="6.54" />
			<item id="167000700" chance="6.54" />
			<item id="167000701" chance="6.54" />
			<item id="167000702" chance="6.54" />
			<item id="167000703" chance="0.79" />
			<item id="167000704" chance="0.39" />
			<item id="167000705" chance="0.39" />
			<item id="167000706" chance="0.79" />
			<item id="167000707" chance="6.54" />
			<item id="167000708" chance="0.39" />
			<item id="167000709" chance="0.79" />
			<item id="167000710" chance="6.54" />
			<item id="167000711" chance="6.54" />
			<item id="167000712" chance="6.54" />
			<item id="167000713" chance="0.79" />
			<item id="167000714" chance="0.39" />
			<item id="167000749" chance="0.39" />
			<item id="167000750" chance="0.39" />
			<item id="167000751" chance="0.39" />
		</set>
	</decomposable>
	<decomposable item_id="188053068" override="true">
		<set>
			<item id="167000685" count="5" chance="15" />
			<item id="167000750" count="5" chance="15" />
			<item id="167000684" count="3" chance="10" />
			<item id="167000749" chance="3" />
			<item id="167000692" count="5" chance="11" />
			<item id="167000695" count="3" chance="3" />
			<item id="167000696" count="3" chance="3" />
			<item id="167000705" chance="2" />
			<item id="167000704" count="4" chance="10" />
			<item id="167000714" count="4" chance="11" />
			<item id="167000697" count="5" chance="17" />
		</set>
	</decomposable>
	<decomposable item_id="188053975" override="true">
		<set player_classes="GLADIATOR">
			<item id="188053750" />
		</set>
		<set player_classes="TEMPLAR">
			<item id="188053751" />
		</set>
		<set player_classes="ASSASSIN">
			<item id="188053752" />
		</set>
		<set player_classes="RANGER">
			<item id="188053753" />
		</set>
		<set player_classes="SORCERER">
			<item id="188053754" />
		</set>
		<set player_classes="SPIRIT_MASTER">
			<item id="188053755" />
		</set>
		<set player_classes="CLERIC">
			<item id="188053756" />
		</set>
		<set player_classes="CHANTER">
			<item id="188053757" />
		</set>
		<set player_classes="RIDER">
			<item id="188053759" />
		</set>
		<set player_classes="GUNNER">
			<item id="188053758" />
		</set>
		<set player_classes="BARD">
			<item id="188053760" />
		</set>
	</decomposable>
	<decomposable item_id="188053976" override="true">
		<set player_classes="GLADIATOR">
			<item id="188053761" />
		</set>
		<set player_classes="TEMPLAR">
			<item id="188053762" />
		</set>
		<set player_classes="ASSASSIN">
			<item id="188053763" />
		</set>
		<set player_classes="RANGER">
			<item id="188053764" />
		</set>
		<set player_classes="SORCERER">
			<item id="188053765" />
		</set>
		<set player_classes="SPIRIT_MASTER">
			<item id="188053766" />
		</set>
		<set player_classes="CLERIC">
			<item id="188053767" />
		</set>
		<set player_classes="CHANTER">
			<item id="188053768" />
		</set>
		<set player_classes="RIDER">
			<item id="188053770" />
		</set>
		<set player_classes="GUNNER">
			<item id="188053769" />
		</set>
		<set player_classes="BARD">
			<item id="188053771" />
		</set>
	</decomposable>
	<decomposable item_id="188053979" override="true">
		<set>
			<item id="140001104" chance="4.5" />
			<item id="140001108" chance="14" />
			<item id="140001105" chance="9.5" />
			<item id="140001106" chance="13" />
			<item id="140001103" chance="5.5" />
			<item id="140001107" chance="3.5" />
			<item id="140001117" chance="1.8" />
			<item id="140001116" chance="2.7" />
			<item id="140001114" chance="5.4" />
			<item id="140001112" chance="6.3" />
			<item id="140001110" chance="5.4" />
			<item id="140001109" chance="3" />
			<item id="140001113" chance="2.7" />
			<item id="140001111" chance="1.8" />
			<item id="140001115" chance="0.9" />
			<item id="140001118" chance="16" />
			<item id="140001119" chance="4" />
		</set>
	</decomposable>
	<decomposable item_id="188053980" override="true">
		<set>
			<item id="140001123" chance="4.5" />
			<item id="140001121" chance="14" />
			<item id="140001124" chance="9.5" />
			<item id="140001125" chance="13" />
			<item id="140001122" chance="5.5" />
			<item id="140001120" chance="3.5" />
			<item id="140001129" chance="1.8" />
			<item id="140001127" chance="2.7" />
			<item id="140001126" chance="5.4" />
			<item id="140001114" chance="6.3" />
			<item id="140001132" chance="5.4" />
			<item id="140001131" chance="3" />
			<item id="140001133" chance="2.7" />
			<item id="140001128" chance="1.8" />
			<item id="140001130" chance="0.9" />
			<item id="140001135" chance="16" />
			<item id="140001134" chance="4" />
		</set>
	</decomposable>
	<decomposable item_id="188053981" override="true">
		<set>
			<item id="140001137" chance="4.5" />
			<item id="140001141" chance="14" />
			<item id="140001140" chance="9.5" />
			<item id="140001136" chance="13" />
			<item id="140001138" chance="5.5" />
			<item id="140001139" chance="3.5" />
			<item id="140001148" chance="1.8" />
			<item id="140001149" chance="2.7" />
			<item id="140001150" chance="5.4" />
			<item id="140001147" chance="6.3" />
			<item id="140001146" chance="5.4" />
			<item id="140001142" chance="3" />
			<item id="140001144" chance="2.7" />
			<item id="140001145" chance="1.8" />
			<item id="140001143" chance="0.9" />
			<item id="140001151" chance="16" />
			<item id="140001152" chance="4" />
		</set>
	</decomposable>
	<decomposable item_id="188053982" override="true">
		<set race="ELYOS">
			<item id="140001155" chance="4.5" />
			<item id="140001153" chance="14" />
			<item id="140001157" chance="9.5" />
			<item id="140001158" chance="13" />
			<item id="140001156" chance="5.5" />
			<item id="140001154" chance="3.5" />
			<item id="140001165" chance="1.8" />
			<item id="140001160" chance="2.7" />
